### ISSUE TITLE
Parsing fab, reth and st interfaces

### ISSUE THREAD

**Issue by jemershaw** [napalm-automation/napalm-yang#126]
It seems like for juniper srx's the fab, reth and st interfaces are not supports to parse the config.
```
No handlers could be found for logger "napalm-yang"
Traceback (most recent call last):
  File "test.py", line 11, in <module>
    running_config.parse_config(native=[config], profile=["junos"])
  File "/Users/jemershaw/workspace/devices/tmp/lib/python2.7/site-packages/napalm_yang/base.py", line 225, in parse_config
    parser.parse()
  File "/Users/jemershaw/workspace/devices/tmp/lib/python2.7/site-packages/napalm_yang/parser.py", line 85, in parse
    self._parse(self._yang_name, self.model, self.mapping[self._yang_name])
  File "/Users/jemershaw/workspace/devices/tmp/lib/python2.7/site-packages/napalm_yang/parser.py", line 91, in _parse
    self._parse_container(attribute, model, mapping)
  File "/Users/jemershaw/workspace/devices/tmp/lib/python2.7/site-packages/napalm_yang/parser.py", line 132, in _parse_container
    self._parse(k, v, mapping[v._yang_name])
  File "/Users/jemershaw/workspace/devices/tmp/lib/python2.7/site-packages/napalm_yang/parser.py", line 93, in _parse
    self._parse_list(attribute, model, mapping)
  File "/Users/jemershaw/workspace/devices/tmp/lib/python2.7/site-packages/napalm_yang/parser.py", line 178, in _parse_list
    self._parse(key, obj, element_mapping)
  File "/Users/jemershaw/workspace/devices/tmp/lib/python2.7/site-packages/napalm_yang/parser.py", line 91, in _parse
    self._parse_container(attribute, model, mapping)
  File "/Users/jemershaw/workspace/devices/tmp/lib/python2.7/site-packages/napalm_yang/parser.py", line 132, in _parse_container
    self._parse(k, v, mapping[v._yang_name])
  File "/Users/jemershaw/workspace/devices/tmp/lib/python2.7/site-packages/napalm_yang/parser.py", line 91, in _parse
    self._parse_container(attribute, model, mapping)
  File "/Users/jemershaw/workspace/devices/tmp/lib/python2.7/site-packages/napalm_yang/parser.py", line 132, in _parse_container
    self._parse(k, v, mapping[v._yang_name])
  File "/Users/jemershaw/workspace/devices/tmp/lib/python2.7/site-packages/napalm_yang/parser.py", line 95, in _parse
    self._parse_leaf(attribute, model, mapping)
  File "/Users/jemershaw/workspace/devices/tmp/lib/python2.7/site-packages/napalm_yang/parser.py", line 194, in _parse_leaf
    value = self.parser.parse_leaf(mapping["_process"], self.bookmarks)
  File "/Users/jemershaw/workspace/devices/tmp/lib/python2.7/site-packages/napalm_yang/parsers/base.py", line 99, in parse_leaf
    result = getattr(self, method_name)(m, data)
  File "/Users/jemershaw/workspace/devices/tmp/lib/python2.7/site-packages/napalm_yang/parsers/jsonp.py", line 116, in _parse_leaf_map
    return mapping['map'][v.lower()]
KeyError: u'fab'
```

**Comment by tcaiazza** [comment]
I think you just have to add those to this mapping https://github.com/napalm-automation/napalm-yang/blob/develop/napalm_yang/mappings/junos/parsers/config/openconfig-interfaces/interfaces.yaml#L36

I'd try it myself if you would post some mock data.  The mock data should be the output of `get configuration` in XML.
