### ISSUE TITLE
FileNotFoundError: [WinError 206] Nom de fichier ou extension trop long: 'C:\\Users\\user\\AppData\\Local\\Temp\\9\\pip-build-71ldn97i\\napalm-yang\\napalm_yang/models/openconfig/network_instances/network_instance/mpls/lsps/constrained_path/named_explicit_paths/named_explicit_path/explicit_route_objects/explicit_route_object/config/'

### ISSUE THREAD

**Issue by lboue** [napalm-automation/napalm-yang#160]
Hello,

I am facing an issue (WinError 206) installing napalm-yang package on Windows7 with Python 3.6.1.

`FileNotFoundError: [WinError 206] Nom de fichier ou extension trop long: 'C:\\Users\\user\\AppData\\Local\\Temp\\9\\pip-build-71ldn97i\\napalm-yang\\napalm_yang/models/openconfig/network_instances/network_instance/mpls/lsps/constrained_path/named_explicit_paths/named_explicit_path/explicit_route_objects/explicit_route_object/config/`

**Full log**
```
C:\Users\user>pip install napalm-yang 
Collecting napalm-yang
  Downloading https://files.pythonhosted.org/packages/c3/bb/65f552c8dea409db2a706e15384bdb0a88af67e74bcc05a13941b6588306
/napalm-yang-0.1.0.tar.gz (4.0MB)
    100% |████████████████████████████████| 4.0MB 6.6MB/s
Exception:
Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python37-32\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\users\user\appdata\local\programs\python\python37-32\lib\site-packages\pip\commands\install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "c:\users\user\appdata\local\programs\python\python37-32\lib\site-packages\pip\req\req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "c:\users\user\appdata\local\programs\python\python37-32\lib\site-packages\pip\req\req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "c:\users\user\appdata\local\programs\python\python37-32\lib\site-packages\pip\download.py", line 821, in unpack_url
    hashes=hashes
  File "c:\users\user\appdata\local\programs\python\python37-32\lib\site-packages\pip\download.py", line 663, in unpack_http_url
    unpack_file(from_path, location, content_type, link)
  File "c:\users\user\appdata\local\programs\python\python37-32\lib\site-packages\pip\utils\__init__.py", line 605, in unpack_file
    untar_file(filename, location)
  File "c:\users\user\appdata\local\programs\python\python37-32\lib\site-packages\pip\utils\__init__.py", line 553, in untar_file
    ensure_dir(path)
  File "c:\users\user\appdata\local\programs\python\python37-32\lib\site-packages\pip\utils\__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "c:\users\user\appdata\local\programs\python\python37-32\lib\os.py", line 221, in makedirs
    mkdir(name, mode)
FileNotFoundError: [WinError 206] Nom de fichier ou extension trop long: 'C:\\Users\\user\\AppData\\Local\\Temp\\9\\pip-build-71ldn97i\\napalm-yang\\napalm_yang/models/openconfig/network_instances/network_instance/mpls/lsps/constrained_path/named_explicit_paths/named_explicit_path/explicit_route_objects/explicit_route_object/config/'

```

Could you help me to fix it or find a workaround?

Regards,
Ludovic

**Comment by dbarrosop** [comment]
Looks like a problem on your OS/shell due to lack of support for long filepaths. Nothing we can do. I'd try using some other shell or a linux VM. I am afraid I haven't worked with windows in 10+ years so I can't help :(
