### ISSUE TITLE
Get napalm-yang out put in ietf format.

### ISSUE THREAD

**Issue by lokmahesh** [napalm-automation/napalm-yang#162]
I am facing one issue while validating yang output from napalm yang against openconfig yang model for interfaces in ODL.
<pre>java.lang.IllegalStateException: Schema node with name ge-0/0/7 wasn't found under (http://openconfig.net/yang/interfaces?revision)interface.
  at org.opendaylight.yangtools.yang.data.codec.gson.JsonParserStream.resolveNamespace(JsonParserStream.java:318)
  at org.opendaylight.yangtools.yang.data.codec.gson.JsonParserStream.read(JsonParserStream.java:219)
  at org.opendaylight.yangtools.yang.data.codec.gson.JsonParserStream.read(JsonParserStream.java:238)
  at org.opendaylight.yangtools.yang.data.codec.gson.JsonParserStream.read(JsonParserStream.java:238)
  at org.opendaylight.yangtools.yang.data.codec.gson.JsonParserStream.parse(JsonParserStream.java:100)
  at com.luminanetworks.lsc.ext.jsonrpc.impl.JsonRPCTx.read(JsonRPCTx.java:186)
  at org.opendaylight.netconf.sal.restconf.impl.BrokerFacade.readDataViaTransaction(BrokerFacade.java:536)
  at org.opendaylight.netconf.sal.restconf.impl.BrokerFacade.readConfigurationData(BrokerFacade.java:172)
  at org.opendaylight.netconf.sal.restconf.impl.RestconfImpl.readConfigurationData(RestconfImpl.java:715)
  at org.opendaylight.netconf.sal.restconf.impl.StatisticsRestconfServiceWrapper.readConfigurationData(StatisticsRestconfServiceWrapper.java:97)
  at org.opendaylight.netconf.sal.rest.impl.RestconfCompositeWrapper.readConfigurationData(RestconfCompos

How can I convert this or get output in standard Json RPC format or IETF format?

**Comment by lokmahesh** [comment]
I am actually trying to get or convert napalm-yang output from openconfig json to json in IETF format something like https://github.com/robshakir/pyangbind

Is there any way we can do it using napalm-yang api?
I am still trying to convert it using following in pyngbind but facing some issues there.
# Dump the static routes instance as JSON in IETF format
print(pybindJSON.dumps(oclr.local_routes, mode="ietf"))

**Comment by dbarrosop** [comment]
I have some code for that but I haven't published it yet (needs some cleaning and testing). I will update you here once I find the time.

**Comment by lokmahesh** [comment]
Thanks,
In case you need any help on that for testing I can help you with that.
I was able to get it using pyangbind for NXOS but still some errors for Junos.

**Comment by dbarrosop** [comment]
Unfortunately I don't have the cycles to keep maintaining this project so as of now it's officially abandoned. If someone wants to fork the project and maintain it don't hesitate to contact me to add a link to the fork and direct existing and new users to the new fork. However, I'd recommend checking the following alternative:

* [yangify](https://github.com/networktocode/yangify)

Yangify has a cleaner interface that is easier to maintain and happens to be orders of magnitude faster and also more memory efficient.

If you are an existing user of napalm-yang and are worried about this announcement and/or want help migrating to some other project don't hesitate to contact me.
