### ISSUE TITLE
Cannot access key when processing list named "property"

### ISSUE THREAD

**Issue by bewing** [napalm-automation/napalm-yang#48]
When attempting to process a list attribute named "property", you cannot use "property_key" to reference the key of the dictionary without the parser returning an error:

```python
Parsing attribute: /components/component[name='TempSensor12/2']/properties/property[name='overheat-threshold']/state/name
Traceback (most recent call last):
  File "test.py", line 30, in <module>
    config.parse_state(native=[json.dumps(plat)], profile=['eos'])
  File "/home/bewing/napalm-yang/napalm_yang/base.py", line 251, in parse_state
    parser.parse()
  File "/home/bewing/napalm-yang/napalm_yang/parser.py", line 75, in parse
    self._parse(self._yang_name, self.model, self.mapping[self._yang_name])
  File "/home/bewing/napalm-yang/napalm_yang/parser.py", line 81, in _parse
    self._parse_container(attribute, model, mapping)
  File "/home/bewing/napalm-yang/napalm_yang/parser.py", line 104, in _parse_container
    self._parse(k, v, mapping[v._yang_name])
  File "/home/bewing/napalm-yang/napalm_yang/parser.py", line 83, in _parse
    self._parse_list(attribute, model, mapping)
  File "/home/bewing/napalm-yang/napalm_yang/parser.py", line 136, in _parse_list
    self._parse(key, obj, element_mapping)
  File "/home/bewing/napalm-yang/napalm_yang/parser.py", line 81, in _parse
    self._parse_container(attribute, model, mapping)
  File "/home/bewing/napalm-yang/napalm_yang/parser.py", line 104, in _parse_container
    self._parse(k, v, mapping[v._yang_name])
  File "/home/bewing/napalm-yang/napalm_yang/parser.py", line 81, in _parse
    self._parse_container(attribute, model, mapping)
  File "/home/bewing/napalm-yang/napalm_yang/parser.py", line 104, in _parse_container
    self._parse(k, v, mapping[v._yang_name])
  File "/home/bewing/napalm-yang/napalm_yang/parser.py", line 83, in _parse
    self._parse_list(attribute, model, mapping)
  File "/home/bewing/napalm-yang/napalm_yang/parser.py", line 136, in _parse_list
    self._parse(key, obj, element_mapping)
  File "/home/bewing/napalm-yang/napalm_yang/parser.py", line 81, in _parse
    self._parse_container(attribute, model, mapping)
  File "/home/bewing/napalm-yang/napalm_yang/parser.py", line 104, in _parse_container
    self._parse(k, v, mapping[v._yang_name])
  File "/home/bewing/napalm-yang/napalm_yang/parser.py", line 81, in _parse
    self._parse_container(attribute, model, mapping)
  File "/home/bewing/napalm-yang/napalm_yang/parser.py", line 104, in _parse_container
    self._parse(k, v, mapping[v._yang_name])
  File "/home/bewing/napalm-yang/napalm_yang/parser.py", line 85, in _parse
    self._parse_leaf(attribute, model, mapping)
  File "/home/bewing/napalm-yang/napalm_yang/parser.py", line 145, in _parse_leaf
    self.extra_vars, None, self.bookmarks)
  File "/home/bewing/napalm-yang/napalm_yang/helpers.py", line 97, in resolve_rule
    rule[k] = template(v, **kwargs)
  File "/home/bewing/napalm-yang/napalm_yang/helpers.py", line 124, in template
    return template.render(**kwargs)
  File "/home/bewing/wat/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/bewing/wat/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 1, in top-level template code
jinja2.exceptions.UndefinedError: 'property_key' is undefined
```
This can be worked around by using "parent_key", if "property" is the parent.

**Comment by dbarrosop** [comment]
Unfortunately I don't have the cycles to keep maintaining this project so as of now it's officially abandoned. If someone wants to fork the project and maintain it don't hesitate to contact me to add a link to the fork and direct existing and new users to the new fork. However, I'd recommend checking the following alternative:

* [yangify](https://github.com/networktocode/yangify)

Yangify has a cleaner interface that is easier to maintain and happens to be orders of magnitude faster and also more memory efficient.

If you are an existing user of napalm-yang and are worried about this announcement and/or want help migrating to some other project don't hesitate to contact me.
